---
AWSTemplateFormatVersion: '2010-09-09'
Description: Main Template to invokes templates for all the stacks 

Parameters:
  VpcId:
    Description: ID of VPC
    Type: AWS::EC2::VPC::Id
  PublicSubnets:
    Description: Choose which subnets the Applicaion Load Balancer should be deployed to
    Type: List<AWS::EC2::Subnet::Id>
  PrivateSubnet:
    Description: Choose which subnet the EC2 Instance should be deployed to
    Type: AWS::EC2::Subnet::Id
  Email:
    Description: Email to receive alarm
    Type: String
    Default: name@abc.com
  ListenerCertificateArn:
    Description: Specify the SSL certificate arn
    Type: String
    Default: arn:aws:acm:ap-northeast-1:<your_account>:certificate/<your_certificate_arn>
Resources:
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://<your_bucket>.s3.amazonaws.com/sg.yaml
      Parameters: 
        EnvironmentName: !Ref AWS::StackName
        VPC: !Ref VpcId
  EC2InstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://<your_bucket>.s3.amazonaws.com/ec2.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        InstanceType: t2.medium
        VPC: !Ref VpcId
        Ec2SecurityGroup: !GetAtt SecurityGroupsStack.Outputs.EC2HostSecurityGroup
        PrivateSubnet: !Ref PrivateSubnet
  ApplicationLoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://<your_bucket>.s3.amazonaws.com/alb.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcId: !Ref VpcId
        PublicSubnets: !Join [ ",", !Ref PublicSubnets ]
        SecurityGroup: !GetAtt SecurityGroupsStack.Outputs.LoadBalancerSecurityGroup
        EC2InstanceId: !GetAtt EC2InstanceStack.Outputs.EC2InstanceId
        ListenerCertificateArn: !Ref ListenerCertificateArn
  CloudWatchStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://<your_bucket>.s3.amazonaws.com/cloudwatch.yaml
      Parameters: 
        EnvironmentName: !Ref AWS::StackName
        EC2InstanceId: !GetAtt EC2InstanceStack.Outputs.EC2InstanceId
        Email: !Ref Email
